apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.APP_NAME }}"
  labels:
    app: "{{ .Values.APP_NAME }}"
data:
  JAVA_OPTS: "{{ .Values.JAVA_OPTS }}"
  ITM_ADVICE_DATABASE_URL: "{{ .Values.ITM_ADVICE_DATABASE_URL }}"
  ITM_ADVICE_KAFKA_HOST: "{{ .Values.ITM_ADVICE_KAFKA_HOST }}"
  ITM_ADVICE_KEYCLOAK_REALM: "{{ .Values.ITM_ADVICE_KEYCLOAK_REALM }}"
  SWAGGER_UI_CLIENT_ID: "{{ .Values.SWAGGER_UI_CLIENT_ID }}"
  SWAGGER_UI_CLIENT_SECRET: "{{ .Values.SWAGGER_UI_CLIENT_SECRET }}"
  ITM_ADVICE_KEYCLOAK_FRONTEND_URL: "{{ .Values.ITM_ADVICE_KEYCLOAK_FRONTEND_URL }}"
  ITM_ADVICE_KEYCLOAK_JWKS_URI: "{{ .Values.ITM_ADVICE_KEYCLOAK_JWKS_URI }}"
  ITM_ADVICE_KEYCLOAK_URL: "{{ .Values.ITM_ADVICE_KEYCLOAK_URL }}"
  LOGGING_CONFIG_FILE: "{{ .Values.LOGGING_CONFIG_FILE }}"