apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.APP_NAME }}"
  labels:
    app: "{{ .Values.APP_NAME }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.APP_NAME }}"
  template:
    metadata:
      name: "{{ .Values.APP_NAME }}"
      labels:
        app: "{{ .Values.APP_NAME }}"
    spec:
      containers:
        - name: "{{ .Values.APP_NAME }}"
          image: "{{ .Values.APP_IMAGE_NAME }}:{{ .Values.APP_IMAGE_TAG }}"
          ports:
            - containerPort: {{ .Values.app.listen.port }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.APP_NAME }}"
          env:
            - name: ITM_ADVICE_SUPPORT_SERVICE_PORT
              value: "8080"
            - name: ITM_ADVICE_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.APP_NAME }}"
                  key: postgres_username
            - name: ITM_ADVICE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.APP_NAME }}"
                  key: postgres_password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
